### ISSUE TITLE
Continuous integration for test-open.ribose.com fails after theme update

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/open.ribose.com#9]
Per @ronaldtse, CI fails with
```
jekyll 3.8.3 | Error:  undefined method `full_gem_path' for nil:NilClass
```

**Comment by strogonoff** [comment]
@ronaldtse 

Pushed theme update which removed non-ASCII symbols from SCSS, in case that was an indirect cause.

If that didn’t help, I think that might have something to do with CI setup on your side. I’m available if my input regarding theme/site implementation would help with troubleshooting.

For the record, it does manage to deploy on my CI to http://hub.ro.dev.anton.strogonoff.name/, with the following scenario (in Gitlab CI format):

```yaml
stages:
- build
- deploy

build:
  image: ruby:2.4.4
  before_script:
  - gem install jekyll bundler
  - bundle --full-index
  script:
  - bundle exec jekyll build
  artifacts:
    paths:
    - _site/

deploy:
  image: python:latest
  before_script:
  - pip install awscli
  script:
  - aws s3 cp _site/ s3://$S3_BUCKET_NAME/ --recursive
  after_script:
  - rm -r _site
```
